name: invitation_generator
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  path_provider: ^2.0.9
  share_plus: ^3.1.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/localization/lang/ar.json
    - lib/localization/lang/en.json

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans-en/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open-sans-en/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open-sans-en/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open-sans-en/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open-sans-en/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open-sans-en/OpenSans-Light.ttf
          weight: 300

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto-sans-ar/NotoSansArabic-Thin.ttf
          weight: 100
